name: build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          submodules: "recursive"
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: npm install
      - uses: peaceiris/actions-hugo@v2
        with:
          extended: true
      - run: make setup ci
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          BLOG_COLLECTION_ID: ${{ secrets.BLOG_COLLECTION_ID }}
          BLOG_COLLECTION_VIEW_ID: ${{ secrets.BLOG_COLLECTION_VIEW_ID }}
          OTHER_COLLECTION_ID: ${{ secrets.OTHER_COLLECTION_ID }}
          OTHER_COLLECTION_VIEW_ID: ${{ secrets.OTHER_COLLECTION_VIEW_ID }}
