name: refresh

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 0 */1 * *"

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make setup refresh
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          BLOG_COLLECTION_ID: ${{ secrets.BLOG_COLLECTION_ID }}
          BLOG_COLLECTION_VIEW_ID: ${{ secrets.BLOG_COLLECTION_VIEW_ID }}
          OTHER_COLLECTION_ID: ${{ secrets.OTHER_COLLECTION_ID }}
          OTHER_COLLECTION_VIEW_ID: ${{ secrets.OTHER_COLLECTION_VIEW_ID }}
      - uses: stefanzweifel/git-auto-commit-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: refresh with notion'
          branch: master
